#!/bin/bash

TEMPLATE="auth0_template.txt"

AUTH0_ID="AUTH0 ACCOUNT ID/INSTANCE ID GOES HERE"
AUTH0_ID_CERT_THUMBPRINT_SHA1="SHA1 GOES HERE"
AUTH0_ID_CERT_THUMBPRINT_SHA256="SHA256 GOES HERE"
AUTH0_ID_CERT_KID="KEY ID GOES HERE"
AUTH0_ID_CERT_MODULUS="MODULUS GOES HERE"
AUTH0_ID_CERT_PE="PUBLIC EXPONENT GOES HERE"
AUTH0_ID_CERT_PEM="CERTIFICATE PEM CONTENT GOES HERE"
AUTH0_ID_CLIENT_ID="CLIENT ID GOES HERE"
AUTH0_ID_CLIENT_SECRET="SECRET GOES HERE"
AUTH0_BIGIP_DNS_RESOLVER="DNS RESOLVER BIGIP CONFIG OBJECT"

SED_ARGS=""
VAR_LIST=`compgen -A variable | grep ^AUTH0_`

for VAR_NAME in ${VAR_LIST} ; do
  SED_ARGS="${SED_ARGS} -e 's#%{${VAR_NAME}}%#${!VAR_NAME}#g'"
done

/bin/bash -c "sed ${SED_ARGS} ${TEMPLATE}"

# EOF
